config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations: 'registrations' }
  root to: "homes#top"
  get 'home/about' => 'homes#about'
  resources :users, only: [:index, :edit, :update, :show]
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy]
end

app/views/shared/_book_detail.html.erb
<h2>Book detail</h2>
<table class="table">
  <tbody>
    <tr>
      <td>
        <%= link_to user, target: "_blank" do %>
          <%= attachment_image_tag user, :profile_image, :fill, 40, 40,
                              format: 'jpeg', fallback: "no_image.jpeg", size:'40x40' %>
          <br>
          <%= user.name %>
        <% end %>
      </td>
      <td>
        <%= link_to book.title, book_path(user) %>
      </td>
      <td>
        <%= book.body %>
      </td>
      <% if user.id == current_user.id %>
        <td>
          <%= link_to "Edit", edit_book_path(book), class: "btn btn-sm btn-success" %>
        </td>
        <td>
          <%= link_to "Destroy", book, class: "btn btn-sm btn-danger", method: :delete, data: { confirm: "本当に消しますか" } %>
        </td>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <div>
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this book from being saved:</h2>
    </div>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<p id="notice">
  <% if flash.any? %>
    <% flash.each do |message_type, message| %>
          <%= message %>
    <% end %>
  <% end %>
</p>

app/views/shared/_post_form.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: book, url: books_path, local:true do |f| %>
  <div class="form-group">
    <label for="title">Title</label>
    <%= f.text_field :title, autofocus: true, class: "form-control book_title" %>
  </div>

  <div class="form-group">
    <label for="body">Opinion</label>
    <%= f.text_area :body, autofocus: true, class: "form-control book_body" %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

app/views/shared/_post_lists.html.erb
<!--<div class="col-md-8 offset-md-1">-->
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% books.each do |book| %>
        <tr>
          <td>
            <%= link_to book.user do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40,
                              format: 'jpeg', fallback: "no_image.jpeg", size:'40x40' %>
            <% end %>
          </td>
          <td>
            <%= link_to book.title, book %>
          </td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<!--</div>-->